#!/bin/bash

DIR=arch-build

if [ ! -d "$DIR" ]; then
   mkdir $DIR
fi

cd $DIR
rm -rf *

# Create grpcToRest.example skeleton bridge project
mvn archetype:generate -B \
   -DarchetypeGroupId=dev.resteasy.grpc \
   -DarchetypeArtifactId=gRPCtoJakartaREST-archetype \
   -DarchetypeVersion=0.0.8-SNAPSHOT \
   -DgroupId=dev.resteasy.examples \
   -DartifactId=grpcToRest.example \
   -Dversion=6.0.0-SNAPSHOT \
   -Dgenerate-prefix=Greet \
   -Dgenerate-package=dev.resteasy.example.grpc.greet \
   -Dresteasy-version=6.3.0.Alpha1-SNAPSHOT \
   -Dgrpc-bridge-version=1.0.0.Alpha1-SNAPSHOT

# Build bridge project
cd grpcToRest.example
mvn install

# Run dev.resteasy.grpc.greet.test.GrpcToJakartaRESTTest, which deploys the bridge project WAR
# to WildFly and makes gRPC invocations on it.
cd ../../arch-test
mvn clean install