#!/bin/bash

DIR=arch-build

echo arch-test-script CLEANING
cd arch-example
mvn clean
cd ../arch-test
mvn clean
cd ..

echo BUILDING arch-example
cd arch-example
mvn install
cd ..

if [ ! -d "$DIR" ]; then
   mkdir $DIR
fi

cd $DIR
rm -rf *
    
echo arch-test-script CREATING grpcToRest.example.grpc
# Create grpcToRest.example skeleton bridge project
mvn archetype:generate -B \
   -DarchetypeGroupId=dev.resteasy.grpc \
   -DarchetypeArtifactId=gRPCtoJakartaREST-archetype \
   -DarchetypeVersion=1.0.0.Final \
   -DgroupId=dev.resteasy.examples \
   -DartifactId=grpcToRest.example \
   -Dversion=1.0.0.Final \
   -Dgenerate-prefix=Greet \
   -Dgenerate-package=dev.resteasy.example.grpc.greet \
   -Dresteasy-version=7.0.0.Final \
   -Dgrpc-bridge-version=1.0.0.Final

# Build bridge project
echo arch-test-script BUILDING grpcToRest.example
cd grpcToRest.example
mvn install

echo arch-test-script TESTING
# Run dev.resteasy.grpc.greet.test.GrpcToJakartaRESTTest, which deploys the bridge project WAR
# to WildFly and makes gRPC invocations on it.
cd ../../arch-test
mvn clean install

echo arch-test-script DONE