#!/bin/bash

DIR=arch-build

echo CLEANING
cd arch-example
mvn clean
cd ../arch-test
mvn clean
cd ..
mvn clean

echo BUILDING arch-example
cd arch-example
mvn install
cd ..

if [ ! -d "$DIR" ]; then
   mkdir $DIR
fi

cd $DIR
rm -rf *
    
echo CREATING grpcToRest.example.grpc
# Create grpcToRest.example skeleton bridge project
mvn archetype:generate -B \
   -DarchetypeGroupId=dev.resteasy.grpc \
   -DarchetypeArtifactId=gRPCtoJakartaREST-archetype \
   -DarchetypeVersion=1.0.0.Alpha8-SNAPSHOT \
   -DgroupId=dev.resteasy.examples \
   -DartifactId=grpcToRest.example \
   -Dversion=1.0.0.Alpha8-SNAPSHOT \
   -Dgenerate-prefix=Greet \
   -Dgenerate-package=dev.resteasy.example.grpc.greet \
   -Dresteasy-version=6.2.11.Final \
   -Dgrpc-bridge-version=1.0.0.Alpha6

# Add resource class for array test
#echo Copying ArrayResource.java
#cp -r ../arch-test/src/main/java/ ../arch-build/grpcToRest.example/src/main/java

# Build bridge project
cd grpcToRest.example
mvn install

# Run dev.resteasy.grpc.greet.test.GrpcToJakartaRESTTest, which deploys the bridge project WAR
# to WildFly and makes gRPC invocations on it.
cd ../../arch-test
mvn clean install